language: php
php:
  - 5.5
  - 5.6
  - 7.0
addons:
  code_climate:
    repo_token: set_me
before_script:
  - sed -i '/phpdoc/d' composer.json
  - composer install
script: phpunit --configuration test/phpunit.xml test
after_script:
  - vendor/bin/test-reporter